steps:
  # Step 1: Build the Docker image
  # The image is tagged with the Git short commit SHA ($SHORT_SHA).
  - name: 'gcr.io/cloud-builders/docker'
    id: 'BUILD'
    args: [
      'build',
      '-t',
      'us-central1-docker.pkg.dev/sdlc-test-project-sbwu/sdlc-demo/cart-app:${SHORT_SHA}',
      './cart-app'  # Path to the directory containing the Dockerfile
    ]

  # Step 2: Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/sdlc-test-project-sbwu/sdlc-demo/cart-app:${SHORT_SHA}'
    id: 'PUSH'
    waitFor: ['BUILD']

  # Step 3: Deploy to GKE using gke-deploy
  - name: "gcr.io/cloud-builders/gke-deploy"
    id: 'DEPLOY'
    args:
      - run
      - --filename=cart-app/deployment.yaml
      - --image=us-central1-docker.pkg.dev/sdlc-test-project-sbwu/sdlc-demo/cart-app:${SHORT_SHA}
      - --cluster=deployment-1-cluster
      - --location=us-central1
      - --project=sdlc-test-project-sbwu
    waitFor: ['PUSH']
  - name: 'ubuntu'
    args: ['sleep', '120']
    id: 'eepy'

# Images to push to Artifact Registry.
# Cloud Build automatically pushes images listed here after the steps are done.
images:
  - 'us-central1-docker.pkg.dev/sdlc-test-project-sbwu/sdlc-demo/cart-app:${SHORT_SHA}'

options:
  requestedVerifyOption: VERIFIED
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
